In [2]:
from Segmentor import Segmentor

Q2_example = "3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione (2.5 g) was added to an ice cooled con. nitric acid (50 ml). After stirring for 1 hr, the reaction mixture was poured into ice-cold water. The yellow crystals were collected by filtration to afford the title compound (0.9 g). The filtrate was extracted by ethyl acetate (200 ml) and washed with brine. The organic phase was dried over anhydrous sodium sulfate. After removal of the solvent, 0.6 g of title compound was obtained as yellow crystal."
Q3_example = "To a rapidly stirred solution of saturated aqueous ammonium hydroxide (50 mL) and ice in a 0 deg. C. bath was added 2,4-dichloro-5-nitropyrimidine (6.0 g, 31 mmol) in portions. The resulting yellow foamy mixture was allowed to stir for 30 min, at which point the precipitate was isolated by filtration. The solid was rinsed several times with ice-cold water and once with ice cold ethanol to give a peach-colored solid. The crude solid was purified by adsorption onto 18 g silica gel, followed by silica gel chromatography, eluting with 0-20% MeOH/dichloromethane to give 2-chloro-5-nitropyrimidin-4-amine as an off-white solid. MS (ES+): 175 (M+H)+; Calc. for C4H3ClN4O2=174.55."

In [5]:
Q2_gpt_4_object = Segmentor("gpt-4", Q2_example)
Q2_gpt_4_object.syn2segment()

[{'text segment': "'3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione (2.5 g) was added to an ice cooled con. nitric acid (50 ml). After stirring for 1 hr, the reaction mixture was poured into ice-cold water.'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up because the main reactant (3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione) is added to the solvent (con. nitric acid) and the reaction condition (ice cooled, stirring for 1 hr) is specified.',
  'step order': '1'},
 {'text segment': "'The yellow crystals were collected by filtration to afford the title compound (0.9 g).'",
  'text class': 'work-up',
  'explanation': 'this is the work-up step because the product is isolated from the reaction mixture by filtration.',
  'step order': '2'},
 {'text segment': "'The filtrate was extracted by ethyl acetate (200 ml) and washed with brine. The organic phase was dried over anhydrous sodium sulf

In [3]:
Q2_gpt_35_object = Segmentor("gpt-3.5-turbo-16k", Q2_example)
Q2_gpt_35_object.syn2segment()

[{'text segment': "'3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione (2.5 g) was added to an ice cooled con. nitric acid (50 ml).'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up step because the main reactant (3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione) and the solvent (ice cooled con. nitric acid) are specified in this sentence.',
  'step order': '1'},
 {'text segment': "'After stirring for 1 hr, the reaction mixture was poured into ice-cold water.'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up step because the duration of the reaction (1 hr) is given in this sentence.',
  'step order': '2'},
 {'text segment': "'The yellow crystals were collected by filtration to afford the title compound (0.9 g).'",
  'text class': 'work-up',
  'explanation': 'this is the work-up step because the sentence describes the process of isolating the desired product 

In [4]:
Q2_anthropicai_object = Segmentor("anthropicai", Q2_example)
Q2_anthropicai_object.syn2segment()

[{'text segment': "'3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione (2.5 g) was added to an ice cooled con. nitric acid (50 ml). After stirring for 1 hr,'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up because the main reactant (3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione) and solvent (nitric acid) were added. Also, the time of the reaction undergoing (stir for 1 hr) is specified in this paragraph.',
  'step order': '1'},
 {'text segment': "'the reaction mixture was poured into ice-cold water. The yellow crystals were collected by filtration to afford the title compound (0.9 g).'",
  'text class': 'work-up',
  'explanation': 'this is the work-up step because the reaction mixture was poured into ice-cold water to stop the reaction and the product (yellow crystals) was collected by filtration.',
  'step order': '2'},
 {'text segment': "'The filtrate was extracted by ethyl acetate (20

In [9]:
Q3_gpt_4_object = Segmentor("gpt-4", Q3_example)
Q3_gpt_4_object.syn2segment()

[{'text segment': "'15 g (0.076 mol) of 2-(Trifluoromethyl)quinoline [prepared from quinoline-2-carboxylic acid according to M. S. Raasch, J. Org. Chem. 27, 1406 (1962)] were hydrogenated in 100 ml of tetrahydrofuran on 2.5 g of ruthenium on alumina (about 10% RU content) at 180° C. for 8 h at an H2 pressure of 80-100 bar in a 0.3 1 V4A autoclave.'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up because the reactant (2-(Trifluoromethyl)quinoline), solvent (tetrahydrofuran), catalyst (ruthenium on alumina), temperature (180° C.), time (8 h), and pressure (80-100 bar) are specified in this segment.',
  'step order': '1'},
 {'text segment': "'After filtration, the THF was stripped off and the crude product was fractionated in a water pump vacuum by means of a microdistillation apparatus.'",
  'text class': 'work-up',
  'explanation': 'this is the work-up step because the paragraph states that the reaction mixture is filtered, the solvent (THF) is removed

In [11]:
Q3_gpt_35_object = Segmentor("gpt-3.5-turbo-16k", Q3_example)
Q3_gpt_35_object.syn2segment()

[{'text segment': "'15 g (0.076 mol) of 2-(Trifluoromethyl)quinoline [prepared from quinoline-2-carboxylic acid according to M. S. Raasch, J. Org. Chem. 27, 1406 (1962)] were hydrogenated in 100 ml of tetrahydrofuran on 2.5 g of ruthenium on alumina (about 10% RU content) at 180° C. for 8 h at an H2 pressure of 80-100 bar in a 0.3 1 V4A autoclave.'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up step because the main reactant (2-(Trifluoromethyl)quinoline), the solvent (tetrahydrofuran), the catalyst (ruthenium on alumina), the reaction conditions (180° C, 8 h, H2 pressure of 80-100 bar), and the reaction vessel (0.3 1 V4A autoclave) are specified in this paragraph.',
  'step order': '1'},
 {'text segment': "'After filtration, the THF was stripped off and the crude product was fractionated in a water pump vacuum by means of a microdistillation apparatus.'",
  'text class': 'work-up',
  'explanation': "this is the work-up step because the THF is remove

In [12]:
Q3_anthropicai_object = Segmentor("anthropicai", Q3_example)
Q3_anthropicai_object.syn2segment()

[{'text segment': "'15 g (0.076 mol) of 2-(Trifluoromethyl)quinoline [prepared from quinoline-2-carboxylic acid according to M. S. Raasch, J. Org. Chem. 27, 1406 (1962)] were hydrogenated in 100 ml of tetrahydrofuran on 2.5 g of ruthenium on alumina (about 10% RU content) at 180° C. for 8 h at an H2 pressure of 80-100 bar in a 0.3 1 V4A autoclave.'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up because the main reactants (2-(Trifluoromethyl)quinoline, ruthenium on alumina), solvent (tetrahydrofuran), catalyst (ruthenium on alumina), temperature (180° C), pressure (80-100 bar), duration (8 h) and equipment (0.3 1 V4A autoclave) are specified in this segment.',
  'step order': '1'},
 {'text segment': "'After filtration, the THF was stripped off and the crude product was fractionated in a water pump vacuum by means of a microdistillation apparatus.'",
  'text class': 'work-up',
  'explanation': 'this is the work-up step because the paragraph states that

In [18]:
import numpy as np
import pandas as pd

model_name = ["gpt-4", "gpt-3.5-turbo-16k", "anthropicai-claude-v1.3"]
paragraph = ["Q2", "Q3"]
data = np.array([41.8, 16.4, 12.1, 56.3, 19.5, 14.7])
new_data = data.reshape(2, 3)
df = pd.DataFrame(new_data, columns=model_name, index=paragraph)
df

gpt-4  gpt-3.5-turbo-16k  anthropicai-claude-v1.3
Q2   41.8               16.4                     12.1
Q3   56.3               19.5                     14.7

To a solution of 7-bromo-4,4-dimethyl-6-hydroxy-1-isopropyl-3,4-dihydronaphthalene (Compound A-30, U.S. Pat. No. 6,613,917, 0.251 g, 0.814 mmol) in acetone (10 mL) at room temperature was added potassium carbonate (422 mg) and iodoethane (0.651 mL, 8.14 mmol), and the resulting solution was stirred at 60° C. for 16 h, then cooled to room temperature. The mixture was diluted with water, extracted with hexane, and washed with 2N NaOH, and brine, dried over MgSO4, and filtered. The solvent was removed under reduce pressure, and the residue was purified by flash column chromatography (silica gel, 98:2 hexane/ethyl acetate) to afford the title compound as a clear oil.

15 g (0.076 mol) of 2-(Trifluoromethyl)quinoline [prepared from quinoline-2-carboxylic acid according to M. S. Raasch, J. Org. Chem. 27, 1406 (1962)] were hydrogenated in 100 ml of tetrahydrofuran on 2.5 g of ruthenium on alumina (about 10% RU content) at 180° C. for 8 h at an H2 pressure of 80-100 bar in a 0.3 1 V4A autoclave. After filtration, the THF was stripped off and the crude product was fractionated in a water pump vacuum by means of a microdistillation apparatus. B.p.16 (main fraction): 88° C. Yield: 12.5 g (0.061 mol) (80% of theory) The product was obtained as a diastereomer mixture. 19F--NMR: δ=+0.65 ppm(d, JH-F =7.1 Hz)(according to integral about 88%) 19F--NMR: δ=+0.90 ppm(d, JH-F =7.1 Hz)(according to integral about 12%) (against external CF3COOH).

To a rapidly stirred solution of saturated aqueous ammonium hydroxide (50 mL) and ice in a 0 deg. C. bath was added 2,4-dichloro-5-nitropyrimidine (6.0 g, 31 mmol) in portions. The resulting yellow foamy mixture was allowed to stir for 30 min, at which point the precipitate was isolated by filtration. The solid was rinsed several times with ice-cold water and once with ice cold ethanol to give a peach-colored solid. The crude solid was purified by adsorption onto 18 g silica gel, followed by silica gel chromatography, eluting with 0-20% MeOH/dichloromethane to give 2-chloro-5-nitropyrimidin-4-amine as an off-white solid. MS (ES+): 175 (M+H)+; Calc. for C4H3ClN4O2=174.55.

Methyl 5-methyl-3-oxo-4-[3-(trifluoromethyl)phenyl]-3,4-dihydropyrazine-2-carboxylate (described in the synthesis of SM2, 1.5 g, 4.8 mmol), dry DCM (7.0 mL), trifluoroacetic acid (3.0 mL) and N-iodosuccinimide (1.0 g, 4.5 mmol) were mixed and stirred at RT in the dark (flask covered with aluminum foil). After 5 h, water (5 mL) was added and the mixture was concentrated by rotary evaporation. Water (3 mL) was added once more and the mixture was concentrated as described above. The resulting mixture was diluted with acetonitrile to a total volume of 50 mL. Purification by preparative HPLC with acetonitrile-water as eluent (neutral eluent) gave 0.905 g (46% yield) of the title compound as a yellow crystalline solid.

Prepared according to procedure T using 4-(3,3-dimethylindolin-6-yl)morpholine (0.2 g, 0.86 mmol), 7,9-dichloro-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline (0.434 g, 1.72 mmol), cesium carbonate (0.561 g, 1.72 mmol), Pd2(dba)3 (0.079 g, 0.086 mmol) and (±) BINAP (0.084 g, 0.129 mmol) in 1,4-dioxane (2 mL). After HPLC purification 7-chloro-9-(3,3-dimethyl-6-(4-morpholinyl)-2,3-dihydro-1H-indol-1-yl)-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline was obtained. 1H NMR (500 MHz, DMSO-d6) δ ppm 8.02 (1H, d, J=9.0 Hz), 7.86 (1H, m), 7.68 (1H, m), 7.06 (1H, m), 6.38 (1H, m), 5.73 (1H, s), 3.86 (2H, d, J=0.5 Hz), 3.73 (2H, s), 3.62 (4H, dd, J=5.4, 4.4 Hz), 3.06 (1H, m), 2.84-2.94 (4H, m), 1.96 (1H, m), 1.33 (12H, m). Mass Spectrum (ESI) m/e=463 (M+1).

In [20]:
Q2_ex1 = "To a solution of (2-methoxyethyl)-5-O-benzoyl-3-deoxy-D-xylofuranose (example 122) (9.59 g, 32.40 mmol) and imidazole (3.980 g, 58.47 mmol) in DMF (40 mL ) at room temperature was added t-butyldimethylsilyl chloride (6.35 g, 42.12 mmol). The solution was stirred for 3 h and saturated NaHCO3 was added. The mixture was concentrated under vacuo. The residue was then partitioned between ether (100 mL) and water (50 mL). The aqueous phase was further extracted with ether (2×50 mL). The combined extracts were washed with brine (2×50 mL) dried (MgSO4) and concentrated to give the title compound (13.3 g, 100%)"
Q2_ex2 = "The title compound was prepared according to the procedure described in step-5 and step-6 of Intermediate-2 by using 1-chloro-2-fluoro-3-iodobenzene (1.0 g, 3.9 mmol), ethynyl(trimethyl)silane (0.541 g, 5.5 mmol), copper iodide (0.027 g, 0.14 mmol), bis(triphenylphosphine) palladium(II) chloride (0.050 g, 0.072 mmol), TBAF (catalytic) and DCM to afford 0.500 g of desired product. 1H NMR (300 MHz, DMSO d6): δ 4.66 (s, 1H), 7.25 (t, J=8.4 Hz, 1H), 7.54 (t, J=7.2 Hz, 1H), 7.65 (t, J=7.8 Hz, 1H)."
Q2_ex3 = "3-(4-chloro-2-fluoro-5-hydroxyphenyl)6-trifluoromethyl-2,4(1H,3H)-pyrmidinedione (2.5 g) was added to an ice cooled con. nitric acid (50 ml). After stirring for 1 hr, the reaction mixture was poured into ice-cold water. The yellow crystals were collected by filtration to afford the title compound (0.9 g). The filtrate was extracted by ethyl acetate (200 ml) and washed with brine. The organic phase was dried over anhydrous sodium sulfate. After removal of the solvent, 0.6 g of title compound was obtained as yellow crystal."
Q2_ex4 = "N-(4-(2-aminoethoxy)-3-(1-methyl-1H-pyrazol-5-yl)phenyl)-3-methoxybenzamide hydrochloride (80.0 mg, 198 μmol), triethylamine (277 μl, 10 eq) and triphosgene (64.8 mg, 1.1 eq) were dissolved in 5 mL of dichloromethane and stirred under reflux for 5 mins. The solvent was removed under vacuum and 4 mL of ethyl acetate was added. It was divided in two and used immediately in the preparation of compound 5 and 7 without purification. LCMS m/z (%)=528 (M+H, 100)."
Q2_ex5 = "This compound was synthesized according to the general method of Compound 50 via iodomethyl 2-butylhexanoate. The product precipitated from the reaction to give Compound 51 (1.44 g, 72%). 1H-NMR (300 MHz, CDCl3) δ 6.96 (3H, m), 6.66 (1H, d), 6.36 (1H, s), 5.81 (2H, s), 5.30 (1H, s), 3.98 (2H, m), 3.78 (6H, m), 3.56 (3H, s), 2.50 (1H, m), 2.31 (3H, s), 1.49-1.72 (4H, m), 1.27-1.35 (8H, m), 0.87 (6H, t)."
Q2_list = [Q2_ex1, Q2_ex2, Q2_ex3, Q2_ex4, Q2_ex5]

In [21]:
Q3_ex1 = "To a solution of 7-bromo-4,4-dimethyl-6-hydroxy-1-isopropyl-3,4-dihydronaphthalene (Compound A-30, U.S. Pat. No. 6,613,917, 0.251 g, 0.814 mmol) in acetone (10 mL) at room temperature was added potassium carbonate (422 mg) and iodoethane (0.651 mL, 8.14 mmol), and the resulting solution was stirred at 60° C. for 16 h, then cooled to room temperature. The mixture was diluted with water, extracted with hexane, and washed with 2N NaOH, and brine, dried over MgSO4, and filtered. The solvent was removed under reduce pressure, and the residue was purified by flash column chromatography (silica gel, 98:2 hexane/ethyl acetate) to afford the title compound as a clear oil."
Q3_ex2 = "15 g (0.076 mol) of 2-(Trifluoromethyl)quinoline [prepared from quinoline-2-carboxylic acid according to M. S. Raasch, J. Org. Chem. 27, 1406 (1962)] were hydrogenated in 100 ml of tetrahydrofuran on 2.5 g of ruthenium on alumina (about 10% RU content) at 180° C. for 8 h at an H2 pressure of 80-100 bar in a 0.3 1 V4A autoclave. After filtration, the THF was stripped off and the crude product was fractionated in a water pump vacuum by means of a microdistillation apparatus. B.p.16 (main fraction): 88° C. Yield: 12.5 g (0.061 mol) (80% of theory) The product was obtained as a diastereomer mixture. 19F--NMR: δ=+0.65 ppm(d, JH-F =7.1 Hz)(according to integral about 88%) 19F--NMR: δ=+0.90 ppm(d, JH-F =7.1 Hz)(according to integral about 12%) (against external CF3COOH)."
Q3_ex3 = "To a rapidly stirred solution of saturated aqueous ammonium hydroxide (50 mL) and ice in a 0 deg. C. bath was added 2,4-dichloro-5-nitropyrimidine (6.0 g, 31 mmol) in portions. The resulting yellow foamy mixture was allowed to stir for 30 min, at which point the precipitate was isolated by filtration. The solid was rinsed several times with ice-cold water and once with ice cold ethanol to give a peach-colored solid. The crude solid was purified by adsorption onto 18 g silica gel, followed by silica gel chromatography, eluting with 0-20% MeOH/dichloromethane to give 2-chloro-5-nitropyrimidin-4-amine as an off-white solid. MS (ES+): 175 (M+H)+; Calc. for C4H3ClN4O2=174.55."
Q3_ex4 = "Methyl 5-methyl-3-oxo-4-[3-(trifluoromethyl)phenyl]-3,4-dihydropyrazine-2-carboxylate (described in the synthesis of SM2, 1.5 g, 4.8 mmol), dry DCM (7.0 mL), trifluoroacetic acid (3.0 mL) and N-iodosuccinimide (1.0 g, 4.5 mmol) were mixed and stirred at RT in the dark (flask covered with aluminum foil). After 5 h, water (5 mL) was added and the mixture was concentrated by rotary evaporation. Water (3 mL) was added once more and the mixture was concentrated as described above. The resulting mixture was diluted with acetonitrile to a total volume of 50 mL. Purification by preparative HPLC with acetonitrile-water as eluent (neutral eluent) gave 0.905 g (46% yield) of the title compound as a yellow crystalline solid."
Q3_ex5 = "Prepared according to procedure T using 4-(3,3-dimethylindolin-6-yl)morpholine (0.2 g, 0.86 mmol), 7,9-dichloro-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline (0.434 g, 1.72 mmol), cesium carbonate (0.561 g, 1.72 mmol), Pd2(dba)3 (0.079 g, 0.086 mmol) and (±) BINAP (0.084 g, 0.129 mmol) in 1,4-dioxane (2 mL). After HPLC purification 7-chloro-9-(3,3-dimethyl-6-(4-morpholinyl)-2,3-dihydro-1H-indol-1-yl)-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline was obtained. 1H NMR (500 MHz, DMSO-d6) δ ppm 8.02 (1H, d, J=9.0 Hz), 7.86 (1H, m), 7.68 (1H, m), 7.06 (1H, m), 6.38 (1H, m), 5.73 (1H, s), 3.86 (2H, d, J=0.5 Hz), 3.73 (2H, s), 3.62 (4H, dd, J=5.4, 4.4 Hz), 3.06 (1H, m), 2.84-2.94 (4H, m), 1.96 (1H, m), 1.33 (12H, m). Mass Spectrum (ESI) m/e=463 (M+1)."
Q3_list = [Q3_ex1, Q3_ex2, Q3_ex3, Q3_ex4, Q3_ex5]

In [27]:
import time

model_name = ["gpt-4", "gpt-3.5-turbo-16k", "anthropicai-claude-v1.3"]
example = ["Ex1", "Ex2", "Ex3", "Ex4", "Ex5"]

In [24]:
Q2_time_list = []


def calculate_Q2():
    for i in range(len(Q2_list)):
        start = time.time()
        Q2_gpt_4_object = Segmentor("gpt-4", Q2_list[i])
        Q2_gpt_4_object.syn2segment()
        end = time.time()
        Q2_time_list.append(end - start)

    for i in range(len(Q2_list)):
        start = time.time()
        Q2_gpt_35_object = Segmentor("gpt-3.5-turbo-16k", Q2_list[i])
        Q2_gpt_35_object.syn2segment()
        end = time.time()
        Q2_time_list.append(end - start)

    for i in range(len(Q2_list)):
        start = time.time()
        Q2_anthropicai_object = Segmentor("anthropicai", Q2_list[i])
        Q2_anthropicai_object.syn2segment()
        end = time.time()
        Q2_time_list.append(end - start)


calculate_Q2()

data = np.array(Q2_time_list)

/home/lance/software/miniconda3/envs/syn2act/lib/python3.9/site-packages/langchain/llms/anthropic.py:134: UserWarning: This Anthropic LLM is deprecated. Please use `from langchain.chat_models import ChatAnthropic` instead
  warnings.warn(


ValueError: Shape of passed values is (3, 5), indices imply (2, 3)

In [31]:
new_data = data.reshape(3, 5)
df_Q2 = pd.DataFrame(new_data, columns=example, index=model_name)
df_Q2

Ex1        Ex2        Ex3        Ex4        Ex5
gpt-4                    51.350837  44.570779  66.334455  46.925668  34.321843
gpt-3.5-turbo-16k        14.752590  14.753291  18.187442  14.718845  12.693321
anthropicai-claude-v1.3  11.233069  11.663896  11.317109  13.642480   9.784524

In [33]:
Q3_time_list = []


def calculate_Q3():
    for i in range(len(Q3_list)):
        start = time.time()
        Q3_gpt_4_object = Segmentor("gpt-4", Q3_list[i])
        Q3_gpt4_results.append(Q3_gpt_4_object.syn2segment())
        end = time.time()
        Q3_time_list.append(end - start)

    for i in range(len(Q3_list)):
        start = time.time()
        Q3_gpt_35_object = Segmentor("gpt-3.5-turbo-16k", Q3_list[i])
        Q3_gpt_35_object.syn2segment()
        end = time.time()
        Q3_time_list.append(end - start)

    for i in range(len(Q3_list)):
        start = time.time()
        Q3_anthropicai_object = Segmentor("anthropicai", Q3_list[i])
        Q3_anthropicai_results.append(Q3_anthropicai_object.syn2segment())
        end = time.time()
        Q3_time_list.append(end - start)


calculate_Q3()

data_Q3 = np.array(Q3_time_list)
new_data_Q3 = data_Q3.reshape(3, 5)
df_Q3 = pd.DataFrame(new_data_Q3, columns=example, index=model_name)
df_Q3

/home/lance/software/miniconda3/envs/syn2act/lib/python3.9/site-packages/langchain/llms/anthropic.py:134: UserWarning: This Anthropic LLM is deprecated. Please use `from langchain.chat_models import ChatAnthropic` instead
  warnings.warn(


Ex1        Ex2        Ex3        Ex4        Ex5
gpt-4                    51.350837  44.570779  66.334455  46.925668  34.321843
gpt-3.5-turbo-16k        14.752590  14.753291  18.187442  14.718845  12.693321
anthropicai-claude-v1.3  11.233069  11.663896  11.317109  13.642480   9.784524

In [35]:
new_data_Q3 = data_Q3.reshape(3, 5)
df_Q3 = pd.DataFrame(new_data_Q3, columns=example, index=model_name)
df_Q3

Ex1        Ex2        Ex3        Ex4        Ex5
gpt-4                    55.156530  60.656772  48.223689  51.886403  73.018801
gpt-3.5-turbo-16k        13.320080  17.674734  15.517937  12.865705  17.088787
anthropicai-claude-v1.3  13.487364  13.863076  14.421516  13.440114  16.964211

In [36]:
Q3_gpt4_results = []
Q3_anthropicai_results = []
for i in range(len(Q3_list)):
    start = time.time()
    Q3_gpt_4_object = Segmentor("gpt-4", Q3_list[i])
    Q3_gpt4_results.append(Q3_gpt_4_object.syn2segment())
    end = time.time()
    Q3_time_list.append(end - start)

In [37]:
for i in range(len(Q3_list)):
    start = time.time()
    Q3_anthropicai_object = Segmentor("anthropicai", Q3_list[i])
    Q3_anthropicai_results.append(Q3_anthropicai_object.syn2segment())
    end = time.time()
    Q3_time_list.append(end - start)

/home/lance/software/miniconda3/envs/syn2act/lib/python3.9/site-packages/langchain/llms/anthropic.py:134: UserWarning: This Anthropic LLM is deprecated. Please use `from langchain.chat_models import ChatAnthropic` instead
  warnings.warn(


Q3_gpt4_results

In [54]:
Q3_gpt4_results[4]

[{'text segment': "'Prepared according to procedure T using 4-(3,3-dimethylindolin-6-yl)morpholine (0.2 g, 0.86 mmol), 7,9-dichloro-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline (0.434 g, 1.72 mmol), cesium carbonate (0.561 g, 1.72 mmol), Pd2(dba)3 (0.079 g, 0.086 mmol) and (±) BINAP (0.084 g, 0.129 mmol) in 1,4-dioxane (2 mL).'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up because the reactants (4-(3,3-dimethylindolin-6-yl)morpholine, 7,9-dichloro-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline, cesium carbonate, Pd2(dba)3, and (±) BINAP) and solvent (1,4-dioxane) are specified along with their amounts and concentrations.',
  'step order': '1'},
 {'text segment': "'After HPLC purification 7-chloro-9-(3,3-dimethyl-6-(4-morpholinyl)-2,3-dihydro-1H-indol-1-yl)-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline was obtained.'",
  'text class': 'purification',
  'explanation': 'this is the purification step because the purification method (HP

In [55]:
Q3_anthropicai_results[4]

[{'text segment': "'Prepared according to procedure T using 4-(3,3-dimethylindolin-6-yl)morpholine (0.2 g, 0.86 mmol), 7,9-dichloro-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline (0.434 g, 1.72 mmol), cesium carbonate (0.561 g, 1.72 mmol), Pd2(dba)3 (0.079 g, 0.086 mmol) and (±) BINAP (0.084 g, 0.129 mmol) in 1,4-dioxane (2 mL).'",
  'text class': 'reaction set-up',
  'explanation': 'this is the reaction set-up because the main reactants (4-(3,3-dimethylindolin-6-yl)morpholine, 7,9-dichloro-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline, cesium carbonate, Pd2(dba)3 and (±) BINAP) and solvent (1,4-dioxane) are specified in this paragraph.',
  'step order': '1'},
 {'text segment': "'After HPLC purification 7-chloro-9-(3,3-dimethyl-6-(4-morpholinyl)-2,3-dihydro-1H-indol-1-yl)-3,3-dimethyl-2,3-dihydro-1H-cyclopenta[b]-quinoline was obtained.'",
  'text class': 'purification',
  'explanation': 'this is the purification step because the purification method (HPLC) is indicated in th